---
version: '3.5'

includes:
  taskotter:
    taskfile: taskotter/Taskfile.yml
    vars:
      YAMLFIX_EXTRA_ARGS: --exclude "taskotter/**/*"

tasks:
  default:
    run: once
    desc: Show all available TaskOtter tasks
    cmds:
      - task --list-all
