---
name: CodSpeed Benchmarks

on:
  push:
    branches:
      - main
  pull_request: null
  workflow_dispatch: null

permissions:
  contents: read

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0
        with:
          go-version-file: go.mod
          cache: false
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@c4fd08a3a159bd0cc208da1e0edf32b8c47d75e5  # v5.4.0
        with:
          mode: walltime
          run: go test -run '^$' -bench . ./...
