---
name: Validate and deploy

on:
  push: null
  workflow_dispatch: null

jobs:
  pipeline:
    name: Validate repository and deploy application
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Update repository tooling with TaskOtter
        uses: $/.github/actions/taskotter
        with:
          github-token: ${{ github.token }}
      - name: Set up Task
        uses: go-task/setup-task@a00fbb05ce67b35648be3c78cbc9fd85354c757e  # v2.2.0
      - name: Apply automated fixes and run CI checks
        uses: $/.github/actions/ci
        with:
          github-token: ${{ github.token }}
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@c4fd08a3a159bd0cc208da1e0edf32b8c47d75e5  # v5.4.0
        with:
          mode: walltime
          run: go test -bench . ./...
